import { LUMUS_CLASS_NAMES, LUMUS_FORM_CLASS_NAMES } from '@/design-system/tokens';

const assistantMessageSurface = 'rounded-3xl rounded-bl-lg border border-slate-200 bg-white shadow-card dark:border-slate-800 dark:bg-slate-900';

/**
 * Contratos visuais do [[Assistente Lumus]].
 *
 * A tela Web e a composição mobile compartilham a mesma linguagem, mas mantêm
 * hierarquia e densidade próprias de cada plataforma.
 */
export const ASSISTANT_CLASS_NAMES = {
	screen: 'flex-1 overflow-hidden bg-slate-50 dark:bg-slate-950',
	panel: 'border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950',
	panelMuted: 'border border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900',
	accentPanel: 'border border-yellow-200 bg-yellow-50 dark:border-yellow-900 dark:bg-yellow-950',
	statusPill: 'min-h-8 flex-row items-center gap-2 rounded-full border border-slate-200 bg-white px-3 dark:border-slate-800 dark:bg-slate-900',
	statusDotAvailable: 'h-2 w-2 rounded-full bg-emerald-500',
	statusDotUnavailable: 'h-2 w-2 rounded-full bg-amber-500',
	toolbar: 'min-h-touch flex-row items-center justify-between gap-3',
	toolbarActions: 'flex-row items-center gap-1',
	iconButton: `${LUMUS_CLASS_NAMES.iconButton} bg-transparent web:transition-colors web:duration-fast web:hover:bg-slate-100 web:active:bg-slate-200 dark:web:hover:bg-slate-800 dark:web:active:bg-slate-700 disabled:opacity-40`,
	accentIconButton: `${LUMUS_CLASS_NAMES.iconButton} bg-yellow-100 web:transition-colors web:duration-fast web:hover:bg-yellow-200 web:active:bg-yellow-300 dark:bg-yellow-950 dark:web:hover:bg-yellow-900 dark:web:active:bg-yellow-800 disabled:opacity-40`,
	conversationFrame: 'w-full max-w-3xl self-center',
	conversationContent: 'gap-5 px-4 pb-8 pt-3 sm:px-6',
	emptyState: 'items-center px-5 py-10',
	emptyMark: 'mb-5 h-16 w-16 items-center justify-center rounded-3xl bg-yellow-100 dark:bg-yellow-950',
	composerDock: 'w-full bg-white px-4 pb-3 pt-3 dark:bg-slate-950 sm:px-6',
	composerShell: 'w-full max-w-3xl self-center rounded-3xl border border-slate-200 bg-slate-50 px-2.5 py-2 shadow-card focus-within:border-lumus-focus focus-within:ring-2 focus-within:ring-lumus-accent dark:border-slate-800 dark:bg-slate-900',
	composerRow: 'flex-row items-end gap-2',
	composerInput: 'max-h-32 min-h-touch flex-1 border-0 bg-transparent',
	composerField: `${LUMUS_CLASS_NAMES.inputText} px-2 py-2.5 text-base leading-5`,
	composerHint: 'mt-2 px-2 text-xs text-slate-500 dark:text-slate-400',
	sendButton: `${LUMUS_CLASS_NAMES.iconButton} bg-lumus-accent web:transition-colors web:duration-fast web:hover:bg-lumus-accent-hover web:active:bg-lumus-accent-pressed disabled:opacity-40`,
	voiceButton: `${LUMUS_CLASS_NAMES.iconButton} bg-white web:transition-colors web:duration-fast web:hover:bg-slate-100 web:active:bg-slate-200 dark:bg-slate-950 dark:web:hover:bg-slate-800 dark:web:active:bg-slate-700 disabled:opacity-40`,
	voiceButtonRecording: `${LUMUS_CLASS_NAMES.iconButton} bg-error-500 disabled:opacity-40`,
	infoBanner: 'flex-row items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 px-4 py-3 dark:border-blue-900 dark:bg-blue-950',
	warningBanner: 'flex-row items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 dark:border-amber-900 dark:bg-amber-950',
	loadingBubble: 'self-start flex-row items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900',
	activityTrace: 'w-full max-w-xl self-start rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900',
	activityTraceToggle: 'min-h-touch flex-row items-center gap-3',
	activityTraceSteps: 'mt-3 gap-2 border-l border-slate-200 pl-3 dark:border-slate-700',
	activityTraceStep: 'min-h-6 flex-row items-center gap-2',
	consentCard: 'w-full max-w-2xl rounded-3xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-950',
	consentItem: 'flex-row items-start gap-3 rounded-2xl bg-slate-50 p-4 dark:bg-slate-900',
	quickPrompt: 'min-h-touch flex-row items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 web:transition-colors web:duration-fast web:hover:border-yellow-400 web:hover:bg-yellow-50 web:active:bg-yellow-100 dark:border-slate-800 dark:bg-slate-900 dark:web:hover:border-yellow-700 dark:web:hover:bg-yellow-950 disabled:opacity-40',
	card: 'w-full overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-card dark:border-slate-800 dark:bg-slate-900',
	cardAttention: 'w-full overflow-hidden rounded-3xl border border-yellow-400 bg-white shadow-card dark:border-yellow-700 dark:bg-slate-900',
	draftCard: `w-full overflow-hidden ${assistantMessageSurface}`,
	cardBody: 'gap-3 p-4 sm:p-5',
	cardHeader: 'flex-row items-center gap-3',
	cardMark: 'h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-yellow-100 dark:bg-yellow-950',
	cardTitle: 'min-w-0 flex-1 text-base font-extrabold text-slate-900 dark:text-slate-100',
	cardMeta: 'text-xs text-slate-500 dark:text-slate-400',
	fieldLabel: 'text-xs font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400',
	inlineFieldLabel: LUMUS_FORM_CLASS_NAMES.label,
	inlineFieldEditor: 'gap-2',
	inlineFieldInput: `${LUMUS_FORM_CLASS_NAMES.input} w-full`,
	inlineFieldInputText: LUMUS_CLASS_NAMES.inputText,
	inlineFieldTextarea: `${LUMUS_FORM_CLASS_NAMES.textarea} w-full`,
	editor: 'gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950',
	choiceRow: 'flex-row flex-wrap gap-2',
	choice: 'min-h-touch justify-center rounded-2xl border border-slate-200 bg-white px-3 py-2 web:transition-colors web:duration-fast web:hover:border-yellow-400 web:hover:bg-yellow-50 dark:border-slate-700 dark:bg-slate-900 dark:web:hover:border-yellow-700 dark:web:hover:bg-yellow-950 disabled:opacity-40',
	choiceText: 'font-bold text-slate-800 dark:text-slate-200',
	mutedInset: 'rounded-2xl bg-slate-100 p-3 dark:bg-slate-800',
	confirmationInset: 'rounded-2xl border border-yellow-200 bg-yellow-50 p-3 dark:border-yellow-900 dark:bg-yellow-950',
	primaryAction: `${LUMUS_CLASS_NAMES.primaryButton} flex-1 px-3 py-3`,
	primaryActionText: `${LUMUS_CLASS_NAMES.primaryButtonText} text-center`,
	secondaryAction: `${LUMUS_CLASS_NAMES.secondaryButton} flex-1 px-3 py-3`,
	dangerAction: 'self-start px-3',
	cardActions: 'flex-row gap-2',
	draftPager: 'w-full gap-3',
	draftPagerButton: 'min-h-touch min-w-touch items-center justify-center rounded-xl border border-slate-300 bg-white px-3 focus-visible:ring-2 focus-visible:ring-lumus-focus disabled:opacity-40 dark:border-slate-700 dark:bg-slate-950',
	draftPagerButtonActive: 'min-h-touch min-w-touch items-center justify-center rounded-xl bg-lumus-accent px-3 focus-visible:ring-2 focus-visible:ring-lumus-focus disabled:opacity-40',
	paginationDock: 'w-full px-4 py-2 sm:px-6',
	paginationDockInner: 'w-full max-w-4xl self-center gap-1',
	paginationDockTitle: 'text-slate-700 dark:text-slate-300',
	paginationDockGroups: 'w-full',
	paginationDockRow: 'min-h-touch flex-row items-center gap-3 py-1',
	paginationDockMeta: 'min-w-32 text-slate-500 dark:text-slate-400',
	metricGrid: 'flex-row flex-wrap gap-2',
	metric: 'min-w-40 flex-1 rounded-2xl bg-slate-50 p-3 dark:bg-slate-950',
	assistantBubble: `max-w-xl self-start gap-2 px-4 py-3 ${assistantMessageSurface}`,
	userBubble: 'max-w-xl self-end gap-2 rounded-3xl rounded-br-lg bg-lumus-accent px-4 py-3 dark:bg-lumus-accent-dark',
	userBubbleText: 'leading-5 text-lumus-on-accent',
	bubbleActions: 'flex-row flex-wrap items-center gap-3',
	bubbleAction: 'min-h-8 flex-row items-center gap-1.5 rounded-lg',
	webLayout: 'relative flex-1 w-screen overflow-hidden bg-slate-50 dark:bg-slate-950',
	webSheet: 'relative z-sheet flex-1 min-h-0 w-full overflow-hidden rounded-t-sheet bg-white px-4 pb-0.5 dark:bg-slate-950 sm:px-6 lg:px-8',
	webWorkspace: 'flex-1 min-h-0 overflow-hidden bg-slate-50 dark:bg-slate-950',
	webHeader: 'bg-white px-4 py-3 dark:bg-slate-950 sm:px-6',
	webHeaderInner: 'w-full max-w-4xl self-center',
	webConversationFrame: 'w-full max-w-4xl self-center',
	webConversationContent: 'gap-5 px-4 pb-10 pt-5 sm:px-6',
	webComposerDock: 'w-full bg-white px-4 pb-4 pt-3 dark:bg-slate-950 sm:px-6',
	webComposer: 'w-full max-w-4xl self-center rounded-3xl border border-slate-200 bg-slate-50 p-2.5 shadow-card dark:border-slate-800 dark:bg-slate-900',
	modal: LUMUS_CLASS_NAMES.modal,
	drawer: LUMUS_CLASS_NAMES.drawer,
} as const;
