import type { ViewStyle } from 'react-native';

export const WEB_DASHBOARD_CLASS_NAMES = {
	screen: 'flex-1 w-screen',
	fill: 'flex-1 w-screen',
	hero: 'absolute inset-x-0 top-0 w-screen overflow-hidden',
	heroImage: 'absolute inset-0 h-full w-full',
	heroContent: 'flex-1 items-center justify-start gap-3.5 px-6',
	heroIllustrationAnimation: 'mx-auto mt-3.5 flex h-2/5 w-full shrink-0 flex-col items-center justify-center',
	heroTitle: 'block w-full max-w-hero-title text-center text-2xl font-extrabold text-white',
	sheet: 'flex-1 w-full rounded-t-sheet px-6 pb-0.5 lg:px-8',
	sheetCompact: 'px-4.5',
	sheetInner: 'flex-1 w-full max-w-content self-center',
	contentFrame: 'w-full max-w-content self-center',
	contentPadding: 'px-6 lg:px-8',
	webSheet: 'web:relative web:z-sheet web:w-full web:rounded-t-sheet web:px-6 web:pb-0.5 web:lg:px-8',
	webSheetCompact: 'web:relative web:z-sheet web:w-full web:rounded-t-sheet web:pb-0.5',
	webContentFrame: 'web:w-full web:max-w-content web:self-center',
	webContentPadding: 'web:px-6 web:lg:px-8',
	bankMovementsContentPadding: 'pt-7',
	scrollContent: 'gap-7 px-6 pb-4.5 pt-4.5 lg:px-8',
	topColumns: 'gap-6.5',
	topColumnsDesktop: 'flex-row',
	topColumnsDesktopCentered: 'justify-center',
	monthlySummaryCards: 'flex-row gap-3',
	monthlySummaryCardsCompact: 'flex-col',
	mandatorySection: 'w-full rounded-section border px-4 pb-4 pt-4',
	mandatorySectionHelper: '-mt-1.5 mb-3.5 text-xs',
	mandatoryColumns: 'flex-row gap-3',
	mandatoryColumnsCompact: 'flex-col',
	mandatoryColumn: 'min-w-0 flex-1 rounded-2xl border p-3',
	mandatoryColumnHeader: 'flex-row items-center gap-2.5',
	mandatoryColumnIcon: 'h-8.5 w-8.5 items-center justify-center rounded-xl',
	mandatoryColumnCopy: 'min-w-0 flex-1',
	mandatoryColumnTitle: 'text-[13px] font-extrabold',
	mandatoryColumnHelper: 'mt-0.5 text-[11px]',
	mandatoryItems: 'mt-3.5 gap-2.5',
	mandatoryItem: 'min-w-0 flex-row items-center gap-2.5',
	mandatoryDateChip: 'min-w-date-chip items-center justify-center rounded-date-chip border px-1.75 py-1.5',
	mandatoryDateText: 'text-center text-2xs font-extrabold',
	mandatoryItemCopy: 'min-w-0 flex-1',
	mandatoryItemName: 'text-[13px] font-bold',
	mandatoryItemMeta: 'mt-0.5 flex-row items-center justify-between gap-2',
	mandatoryItemInstallment: 'min-w-0 flex-1 text-2xs',
	mandatoryItemAmount: 'text-xs font-extrabold tabular-nums',
	mandatoryEmptyText: 'mt-3.5 text-xs',
	mandatorySkeleton: 'h-31.5 flex-1 rounded-2xl',
	monthlySummaryCard: 'min-h-summary-card flex-1 rounded-summary border px-4.5 py-4',
	monthlySummaryCardContent: 'flex-1 flex-row items-center gap-3',
	monthlySummaryCopy: 'min-w-0 flex-1',
	monthlySummaryPeriod: 'text-2xs font-extrabold uppercase tracking-label',
	monthlySummaryLabel: 'mt-2.5 text-[13px] font-bold',
	monthlySummaryValue: 'mt-1 text-[21px] font-extrabold',
	monthlySummaryHelper: 'mt-1.5 text-xs',
	expenseChartSection: 'w-full rounded-section border px-3 pb-1.5 pt-4',
	expenseChartHelper: '-mt-1 mb-0.5 text-xs',
	expenseChartSkeleton: 'mt-3 h-chart w-full rounded-chart',
	activityHeatmapSection: 'w-full rounded-section border px-3 pb-3 pt-4',
	activityHeatmapHelper: '-mt-1 mb-2.5 text-xs',
	activityHeatmapSkeleton: 'h-heatmap w-full rounded-chart',
	section: 'mb-1',
	columnSection: 'min-w-0 flex-1',
	bankSection: 'flex-col',
	bankSectionCentered: 'w-full max-w-bank-card flex-none self-center',
	sectionHeading: 'mb-3 min-h-8.5 flex-row items-center gap-1.25',
	headingWithTip: 'flex-1 flex-row items-center gap-1.25',
	sectionHeadingText: 'text-[17px] font-extrabold uppercase tracking-section',
	infoButton: 'h-6 w-6 items-center justify-center',
	popoverBackdrop: 'bg-transparent',
	tooltip: 'max-w-tooltip rounded-xl',
	tooltipText: 'text-xs leading-[19px] text-slate-200',
	bankCardPressable: 'min-h-bank-card w-full flex-1',
	bankCard: 'min-h-bank-card flex-1',
	bankCardContent: 'flex-1 justify-between p-4.5',
	cardKicker: 'text-2xs font-bold uppercase tracking-kicker',
	bankName: 'mt-1 text-xl font-extrabold',
	bankBalance: 'mt-1 text-[22px] font-extrabold',
	bankCardFooter: 'flex-row justify-between gap-4.5',
	bankFooterRight: 'items-end',
	bankFooterValue: 'mt-0.5 text-[13px] font-bold',
	investmentVisual: 'items-center',
	chartCenter: 'items-center justify-center',
	chartLabel: 'text-2xs font-bold tracking-wide',
	chartCount: 'mt-0.5 text-3xl font-extrabold',
	chartCaption: 'mt-px text-[11px]',
	investmentTotals: 'mt-4 w-full flex-row justify-between',
	totalRight: 'items-end',
	totalLabel: 'text-2xs font-bold uppercase tracking-kicker',
	totalValue: 'mt-1 text-[17px] font-extrabold',
	timeline: 'mt-0.5',
	timelineRow: 'min-h-timeline-row flex-row',
	timelineRail: 'w-7 items-center pb-0 pt-2',
	timelineDot: 'h-3.25 w-3.25 rounded-full border-2 border-white',
	timelineLine: 'my-0.5 w-0.75 flex-1 rounded-full',
	timelineBody: 'flex-1 pb-3.5',
	movementHeader: 'flex-row items-center justify-between gap-3',
	movementIdentity: 'min-w-0 flex-1 flex-row items-center gap-3',
	movementIcon: 'h-11 w-11 items-center justify-center rounded-movement-icon',
	movementCopy: 'min-w-0 flex-1',
	movementName: 'text-[15px] font-bold',
	movementSubtitle: 'mt-0.5 text-xs opacity-muted',
	movementAmount: 'items-end',
	amount: 'text-[15px] font-bold',
	movementDate: 'mt-1 flex-row items-center gap-1',
	dateText: 'text-[11px] text-slate-400',
	movementDetailAnimation: 'w-full self-stretch overflow-hidden rounded-summary',
	movementDetail: 'relative mt-2.5 w-full overflow-hidden rounded-summary',
	movementDetailGrainient: 'absolute inset-0 h-full w-full rounded-summary opacity-95',
	movementDetailContent: 'relative z-content px-4 py-3.5',
	detailGrid: 'mt-3.5 flex-row flex-wrap gap-3',
	detailItem: 'w-[45%] min-w-detail-item',
	detailLabel: 'text-2xs font-bold uppercase tracking-detail text-white/70',
	detailText: 'mt-1 text-[13px] leading-[18px] text-white',
	emptyText: 'py-4 text-[13px] leading-5',
	emptyMovement: 'rounded-2xl border p-4.5',
	inlineError: 'mt-2 text-[13px] leading-5',
	errorText: 'text-amber-500',
	gainValue: 'text-lumus-income-light dark:text-lumus-income-dark',
	simulatedValue: 'text-emerald-400',
	expenseValue: 'text-lumus-expense-light dark:text-lumus-expense-dark',
	skeletonShort: 'h-3 w-27.5',
	skeletonLong: 'mt-3 h-7 w-45',
	skeletonBalance: 'mt-10 h-8.5 w-37.5',
	investmentSkeleton: 'items-center gap-4.5 py-5',
	skeletonDonut: 'h-47.5 w-47.5',
	timelineSkeleton: 'gap-4.5',
	skeletonRow: 'flex-row items-center gap-3.5',
	skeletonDot: 'h-10.5 w-10.5',
	skeletonText: 'h-7.5 flex-1',
} as const;

export const WEB_DASHBOARD_DOM_STYLES: Record<string, ViewStyle> = {
	sparkline: { width: 112, height: 52, backgroundColor: 'transparent' },
	expenseLineChart: { height: 326, width: '100%', backgroundColor: 'transparent' },
	activityHeatmap: { minHeight: 190, width: '100%', backgroundColor: 'transparent' },
};
